### ISSUE TITLE
 termsrv.dll 10.0.18362.1316，该版本不支持

### ISSUE THREAD

**Issue by Passerby1011** [anhkgg/SuperRDP#1]

**Comment by ccdos** [comment]
> 1
[+] Select option 1, install...
[*] Installing...
[+] termsrv.dll 10.0.19041.746
[-] Not support the version of termsrv, please contact author to update.
请按任意键继续. . .


不过我是想试试 这个补丁 是否可以支持专业版的 多用户远程

**Comment by anhkgg** [comment]
版本太老了，我没弄过，所以没配置，你可以升级一下系统。

如果你缺失需要这个版本，可以吧termsrv.dll这个文件给我，我给你升级一下。
