### ISSUE TITLE
同一个应用无法在两个账户里同时打开

### ISSUE THREAD

**Issue by jupitersh** [anhkgg/SuperRDP#107]
系统：win11
本地账户打开chrome后，远程账户想要打开chrome就无法打开，远程账户双击chrome会在本地账户里打开chrome；反过来，远程账户先打开chrome的话，本地账户想打开chrome也会出现这样的问题。
edge等其他应用也会这样，希望能尽快修复。

**Comment by nftbty** [comment]
你的本地用户和远程用户是同一个吧，开了multi session per user ？基于chromium的浏览器都存在这个问题，这是软件本身就不支持单用户多会话模式。
还有，这个软件只是强制开启了系统rdp的多会话功能，至于在使用过程中，除了多会话功能开启不正常，其他问题都与这个工具无关，属于系统rdp本身或者所用软件的问题。

**Comment by jupitersh** [comment]
不是同一个账户，是两个不一样的账户
