### ISSUE TITLE
10.0.18362.2158 #103安装出错

### ISSUE THREAD

**Issue by nba408410041** [anhkgg/SuperRDP#113]
Dear Sir, I am using your developed
support 10.0.18362.2158 #103 There is an error in the installation prompt
<img width="479" alt="1F41A025-28EA-4370-95B9-537A759D1051" src="https://user-images.githubusercontent.com/50854420/167374359-a0b266e1-72e1-4449-b42a-7f134ac22aad.png">

**Comment by anhkgg** [comment]
Maybe you can kill the antivirus software and retry
