### ISSUE TITLE
不支持19043

### ISSUE THREAD

**Issue by asheigithub** [anhkgg/SuperRDP#117]
![image](https://user-images.githubusercontent.com/15963682/167866860-cf27086a-4c08-47a5-8fc2-95c537b43181.png)
如图如下配置不支持。。
使用自动分析后，程序被报毒并被杀，但是远程桌面又成功的开启了

**Comment by anhkgg** [comment]
开启自动分析就会安装，所以已经安装成功了。
被杀了就加白一下。
