### ISSUE TITLE
Why is there an Anti-VM Check?

### ISSUE THREAD

**Issue by SmilerRyan** [anhkgg/SuperRDP#118]
I would like to use this RDP Wrapper on my virtual machine,
Why would the program be set to not be allowed on virtual machines?

![image](https://user-images.githubusercontent.com/14893385/167969360-499f0118-3cef-433d-a09f-94bf1417a231.png)

**Comment by anhkgg** [comment]
[SuperRDP2_2.0.0.35.zip](https://github.com/anhkgg/SuperRDP/files/8674363/SuperRDP2_2.0.0.35.zip)
