### ISSUE TITLE
Support for 10.0.19041.1021

### ISSUE THREAD

**Issue by SmilerRyan** [anhkgg/SuperRDP#121]
Running SuperRDP 2.0.0.35 and synced the latest config.

![screenshot](https://user-images.githubusercontent.com/14893385/168031560-6be8007e-567d-4807-a981-9f2d4983fb8b.png)

Download of my config+dll from "share to github" link: [10.0.19041.1021.zip](https://github.com/anhkgg/SuperRDP/files/8676408/10.0.19041.1021.zip)

**Comment by anhkgg** [comment]
select checkbox AutoSupport, and then install

**Comment by SmilerRyan** [comment]
> select checkbox AutoSupport, and then install

It tells me to use wechat (I don't have an account on there), and clicking "How to get code?" seems to not open anything.

**Comment by anhkgg** [comment]
type the code 1869E4 when your localtime is 2022-05-13 10:00.

And you can get the new version 2.0.0.36.
