### ISSUE TITLE
os version 10.0.22000.675

### ISSUE THREAD

**Issue by danielpm307** [anhkgg/SuperRDP#123]
[termsrv.zip](https://github.com/anhkgg/SuperRDP/files/8681530/termsrv.zip)
hi , I cant access to WeChat , I sent it here , thanks for updating it . 
![image](https://user-images.githubusercontent.com/1260701/168138708-cee094da-a2b0-4289-b760-549f948a5503.png)

thanks .

**Comment by anhkgg** [comment]
You can type the code 1869E4 when your localtime is 2022-05-13 10:00.

**Comment by danielpm307** [comment]
thanks for that; I change my computer Clock to this date and time, but it prints an error. (I tried it in PM an AM )

**Comment by danielpm307** [comment]
I modified my file 
fixed. 

[termsrv.zip](https://github.com/anhkgg/SuperRDP/files/8688791/termsrv.zip)
