### ISSUE TITLE
10.0.19041.1682 not work

### ISSUE THREAD

**Issue by brumegoo** [anhkgg/SuperRDP#124]
[termsrv.zip](https://github.com/anhkgg/SuperRDP/files/8684114/termsrv.zip)
10.0.19041.1682 not work

**Comment by anhkgg** [comment]
You can try the lastest version 2.0.0.36

**Comment by brumegoo** [comment]
the lastest version 2.0.0.36 not work,too

**Comment by anhkgg** [comment]
Open autosupport
