### ISSUE TITLE
"Not support the version of termsrv, please contact author to update."

### ISSUE THREAD

**Issue by ricardovalmada** [anhkgg/SuperRDP#126]
[termsrv_10.0.19041.1682_W10PRO_X64.zip](https://github.com/anhkgg/SuperRDP/files/8690916/termsrv_10.0.19041.1682_W10PRO_X64.zip)

**Comment by GrayXu** [comment]
Same problem after update win10 to 19044.1706 (10.0.19041.1682). @anhkgg 

```
Please select option:
    1: Install SuperRDP to Program Files folder (default)
    2: Uninstall SuperRDP
    3: Force restart Terminal Services

> 1
[+] Select option 1, install...
[*] Installing...
[+] termsrv.dll 10.0.19041.1682
[-] Not support the version of termsrv, please contact author to update.
```

Thanks so much for following

**Comment by anhkgg** [comment]
下载[SuperRDP2](https://raw.githubusercontent.com/anhkgg/SuperRDP/main/bin/SuperRDP2.zip)，开启自动分析就行了。
