### ISSUE TITLE
Translation into other languages

### ISSUE THREAD

**Issue by paolosezart** [anhkgg/SuperRDP#127]
Is it possible to make an optional translation of SuperRDP2 into English? 
Thanks!

**Comment by anhkgg** [comment]
SuperRDP will show english not in Chinese environment

**Comment by ricardovalmada** [comment]
Not working bro, Brazilian Portuguese here and it's showing in Chinese, plus i'm getting script errors after opening app. I don't know which option i have to choose.
![Chinese](https://user-images.githubusercontent.com/97296257/168510444-c3286a9b-ecb3-4bef-b4f2-54f2d6474538.png)
![Script error](https://user-images.githubusercontent.com/97296257/168510445-e0b50aff-d50e-44c2-ae4c-7ca5debd3fc2.png)

**Comment by anhkgg** [comment]
thk, I fixed it. You can download the new version 2.0.0.38
