### ISSUE TITLE
请添加10.0.19041.1682 的支持

### ISSUE THREAD

**Issue by HuangHHheng** [anhkgg/SuperRDP#131]
[termsrv.zip](https://github.com/anhkgg/SuperRDP/files/8696892/termsrv.zip)

**Comment by anhkgg** [comment]
下载superrdp2

**Comment by HuangHHheng** [comment]
您好，我下载了最新的版本，但是，同步最近配置之后，依旧安装失败
![Uploading image.png…]()

**Comment by anhkgg** [comment]
勾选自动分析
