### ISSUE TITLE
can't support  .19041.1682

### ISSUE THREAD

**Issue by julyaoao** [anhkgg/SuperRDP#134]
[+] Select option 1, install...
[*] Installing...
[+] termsrv.dll 10.0.19041.1682
[-] Not support the version of termsrv, please contact author to update.

**Comment by julyaoao** [comment]
[termsrv.txt](https://github.com/anhkgg/SuperRDP/files/8698985/termsrv.txt)

rename to .dll

**Comment by anhkgg** [comment]
hi, you can download [SuperRDP2](https://raw.githubusercontent.com/anhkgg/SuperRDP/main/bin/SuperRDP2.zip) to open AutoSupport.
