### ISSUE TITLE
Windows 11 21H2 OS Build 1000.2200.675.0

### ISSUE THREAD

**Issue by MagicIIFL** [anhkgg/SuperRDP#136]
Windows 11 21H2 OS Build 1000.2200.675.0
[](url
[termsrv.zip](https://github.com/anhkgg/SuperRDP/files/8701667/termsrv.zip)
)

**Comment by anhkgg** [comment]
try the new version: https://raw.githubusercontent.com/anhkgg/SuperRDP/main/bin/SuperRDP2.zip
