### ISSUE TITLE
não está funcionando no win10 21h2 19044.1645

### ISSUE THREAD

**Issue by Natanaelb906** [anhkgg/SuperRDP#137]
![SuperRDP2 _ www hankeer org 19_05_2022 11_11_05 (1)](https://user-images.githubusercontent.com/105863189/169316491-f4f333c0-0147-4e29-bd59-2f7011eef2e0.png)

Não funciona nessa versão...

**Comment by Natanaelb906** [comment]
[termsr.dll - txt.txt](https://github.com/anhkgg/SuperRDP/files/8730358/termsr.dll.-.txt.txt)

**Comment by anhkgg** [comment]
I see the 3389 is YES, why not work?
