### ISSUE TITLE
New version of termsrv.dll 10.0.22000.675 on windows 11

### ISSUE THREAD

**Issue by Garciasondro** [anhkgg/SuperRDP#139]
Hi, I updated to the latest windows 11 and it says "not support the version of termsrv, please contact author to update".
Would you please update it? Thank you!
[termsrv.zip](https://github.com/anhkgg/SuperRDP/files/8752655/termsrv.zip)

**Comment by anhkgg** [comment]
You can download https://raw.githubusercontent.com/anhkgg/SuperRDP/main/bin/SuperRDP2.zip, and set check box AutoSupport
