### ISSUE TITLE
请问支持 19042.631 吗

### ISSUE THREAD

**Issue by ShengzhenFu** [anhkgg/SuperRDP#14]
@anhkgg 支持19042.631吗
![image](https://user-images.githubusercontent.com/30173222/122691763-2ab50100-d264-11eb-8ff6-81fcbba91f48.png)

![image](https://user-images.githubusercontent.com/30173222/122691728-09ecab80-d264-11eb-9dae-b28d08e923dc.png)

**Comment by anhkgg** [comment]
你试试吧，把system32\termsrv.dll传来
