### ISSUE TITLE
win11最新不支持 10.0.22621.1

### ISSUE THREAD

**Issue by haomingzhan** [anhkgg/SuperRDP#140]
[+] Select option 1, install...
[*] Installing...
[+] termsrv.dll 10.0.22621.1
[-] Not support the version of termsrv, please contact author to update.

[termsrv.zip](https://github.com/anhkgg/SuperRDP/files/8762566/termsrv.zip)

**Comment by anhkgg** [comment]
下载https://raw.githubusercontent.com/anhkgg/SuperRDP/main/bin/SuperRDP2.zip, 开始自动分析
