### ISSUE TITLE
termsrv.dll 10.0.22000.708

### ISSUE THREAD

**Issue by acacy73** [anhkgg/SuperRDP#144]
SuperRDP2_2.0.0.38 is not support termsrv.dll 10.0.22000.708

**Comment by acacy73** [comment]
[](url
[termsrv.zip](https://github.com/anhkgg/SuperRDP/files/8813136/termsrv.zip)
)

**Comment by anhkgg** [comment]
https://raw.githubusercontent.com/anhkgg/SuperRDP/main/bin/SuperRDP2.zip，check AutoSupport

**Comment by acacy73** [comment]
Thanks, Please share AutoSupport code.
