### ISSUE TITLE
10.0.22000.708无法分析

### ISSUE THREAD

**Issue by copurxia** [anhkgg/SuperRDP#145]
无论是同步最新配置还是开启自动分析均失败
点击安装时提示不支持

**Comment by anhkgg** [comment]
[10.0.22000.708]
LocalOnlyPatch.x64=1
LocalOnlyOffset.x64=98CB1
LocalOnlyCode.x64=jmpshort
SingleUserPatch.x64=1
SingleUserOffset.x64=18F22
SingleUserCode.x64=Zero
DefPolicyPatch.x64=1
DefPolicyOffset.x64=1BA15
DefPolicyCode.x64=CDefPolicy_Query_eax_rcx
SLInitHook.x64=1
SLInitOffset.x64=26C10
SLInitFunc.x64=New_CSLQuery_Initialize

[10.0.22000.708-SLInit]
bInitialized.x64 =11FECC
bServerSku.x64 =11FED0
lMaxUserSessions.x64 =11FED4
bAppServerAllowed.x64 =11FEDC
bRemoteConnAllowed.x64=11FEE4
bMultimonAllowed.x64 =11FEE8
ulMaxDebugSessions.x64=11FEF0
bFUSEnabled.x64 =11FEF4
