### ISSUE TITLE
Support for 10.0.22000.708

### ISSUE THREAD

**Issue by pkejval** [anhkgg/SuperRDP#146]
Please add support for newest version 10.0.22000.708. Files in attachment.

[10.0.22000.708.zip](https://github.com/anhkgg/SuperRDP/files/8830655/10.0.22000.708.zip)

**Comment by anhkgg** [comment]
[10.0.22000.708]
LocalOnlyPatch.x64=1
LocalOnlyOffset.x64=98CB1
LocalOnlyCode.x64=jmpshort
SingleUserPatch.x64=1
SingleUserOffset.x64=18F22
SingleUserCode.x64=Zero
DefPolicyPatch.x64=1
DefPolicyOffset.x64=1BA15
DefPolicyCode.x64=CDefPolicy_Query_eax_rcx
SLInitHook.x64=1
SLInitOffset.x64=26C10
SLInitFunc.x64=New_CSLQuery_Initialize

[10.0.22000.708-SLInit]
bInitialized.x64 =11FECC
bServerSku.x64 =11FED0
lMaxUserSessions.x64 =11FED4
bAppServerAllowed.x64 =11FEDC
bRemoteConnAllowed.x64=11FEE4
bMultimonAllowed.x64 =11FEE8
ulMaxDebugSessions.x64=11FEF0
bFUSEnabled.x64 =11FEF4
