### ISSUE TITLE
termsrv.dll 10.0.19041.1741 目前不支持

### ISSUE THREAD

**Issue by JerryABigRat** [anhkgg/SuperRDP#149]
如题，该版本的termsrv.dll尚未支持，麻烦作者更新一下配置文件呢~非常感谢卡！
![Issue1](https://user-images.githubusercontent.com/70056152/172527510-d0b17e4a-b5ef-4661-b371-3e414b022199.jpg)

**Comment by anhkgg** [comment]
用2.0吧，https://raw.githubusercontent.com/anhkgg/SuperRDP/main/bin/SuperRDP2.zip，开启自动分析
