### ISSUE TITLE
update ini file for version 10.0.19041.1081

### ISSUE THREAD

**Issue by Rodrigocg** [anhkgg/SuperRDP#15]
Add in ini file:

`[10.0.19041.1081]
LocalOnlyPatch.x64=1
LocalOnlyOffset.x64=89D81
LocalOnlyCode.x64=jmpshort
SingleUserPatch.x64=1
SingleUserOffset.x64=0CB26
SingleUserCode.x64=Zero
DefPolicyPatch.x64=1
DefPolicyOffset.x64=19105
DefPolicyCode.x64=CDefPolicy_Query_eax_rcx
SLInitHook.x64=1
SLInitOffset.x64=1E98C
SLInitFunc.x64=New_CSLQuery_Initialize

[10.0.19041.1081-SLInit]
bInitialized.x64      =107108
bServerSku.x64        =10710C
lMaxUserSessions.x64  =107110
bAppServerAllowed.x64 =107118
bRemoteConnAllowed.x64=107120
bMultimonAllowed.x64  =107124
ulMaxDebugSessions.x64=107128
bFUSEnabled.x64       =10712C`

I tested the modification on the file and it worked correctly.

Source: [https://github.com/stascorp/rdpwrap/issues/1454](url)

**Comment by anhkgg** [comment]
Thanks.
My os just updated to 10.0.19042.1083, and I update the rdpwrap.ini also.
