### ISSUE TITLE
19044.1741

### ISSUE THREAD

**Issue by yanjiujun** [anhkgg/SuperRDP#150]
大佬帮忙处理下
[termsrv.dll.zip](https://github.com/anhkgg/SuperRDP/files/8877529/termsrv.dll.zip)

**Comment by anhkgg** [comment]
用https://raw.githubusercontent.com/anhkgg/SuperRDP/main/bin/SuperRDP2.zip，开启自动分析

**Comment by kaqiubiqiu** [comment]
大佬，你写的程序我的服务器防火墙一直杀，请你帮忙更新下这个版本系统的文档吧，今天远程崩到不行。  termsrv.dll.zip 
 10.0.19041.1741
