### ISSUE TITLE
无法自动分析

### ISSUE THREAD

**Issue by cay080801** [anhkgg/SuperRDP#152]
提示口令错误 口令是刚获取的FD547F

**Comment by cay080801** [comment]
![image](https://user-images.githubusercontent.com/62632733/174227614-a6c237d4-b36e-410b-a634-b3ccec47f058.png)

**Comment by cay080801** [comment]
另外 电脑的时间是对的

**Comment by cay080801** [comment]
另外的 我发现我突然不能用远程桌面了
（我是专业版……）

**Comment by cay080801** [comment]
> 另外的 我发现我突然不能用远程桌面了
> （我是专业版……）

淦 是我傻了 不小心把远程桌面关了
但口令错误的问题还没解决

**Comment by cay080801** [comment]
[termsrv.zip](https://github.com/anhkgg/SuperRDP/files/8924776/termsrv.zip)
![image](https://user-images.githubusercontent.com/62632733/174231897-0127ad98-211c-4643-aac5-160910660d7c.png)

**Comment by xrn1997** [comment]
我也碰到这问题了，口令错误。

**Comment by anhkgg** [comment]
已经恢复了

**Comment by cay080801** [comment]
大佬厉害！
