### ISSUE TITLE
开启自动分析失败

### ISSUE THREAD

**Issue by yjmoming** [anhkgg/SuperRDP#157]
开启自动分析一直提示'Code Error'.试过重新获取CODE，也试地换目录都无法解决。

**Comment by anhkgg** [comment]
英语环境？看英语帮助

**Comment by yjmoming** [comment]
是英文环境，已解决code的问题。
但还是无法支持win 11。怎么处理呢？



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "anhkgg/SuperRDP"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年6月21日(星期二) 中午11:49
***@***.***&gt;;
抄送:&nbsp;"James ***@***.******@***.***&gt;;
主题:&nbsp;Re: [anhkgg/SuperRDP] 开启自动分析失败 (Issue #157)





 
英语环境？看英语帮助

**Comment by yjmoming** [comment]
是英文环境，已解决code的问题。
但还是无法支持win 11。怎么处理呢？
![微信图片_20220621120643](https://user-images.githubusercontent.com/42855866/174714187-bd1fad95-edbc-4a7a-8652-12cf085f3f64.png)

**Comment by anhkgg** [comment]
我看3389已经正常工作了，还是无法远程吗？

**Comment by yjmoming** [comment]
是的，还是无法远程。
