### ISSUE TITLE
win10 10.0.19041.1682 termsrv 

### ISSUE THREAD

**Issue by KingAndJiang** [anhkgg/SuperRDP#160]
win10 10.0.19041.1682  termsrv 版本不支持SuperRDP

**Comment by KingAndJiang** [comment]
![image](https://user-images.githubusercontent.com/74846567/175011237-bc7c4a48-9d5e-4738-9f68-1ea3a4a05243.png)

**Comment by KingAndJiang** [comment]
https://github.com/KingAndJiang/termsrv#termsrv

**Comment by KingAndJiang** [comment]
c:\windows\system32\termsrv.dll的文件地址https://github.com/KingAndJiang/termsrv#termsrv

**Comment by KingAndJiang** [comment]
termsrv.dll
[10.0.19041.1682..zip](https://github.com/anhkgg/SuperRDP/files/8964640/10.0.19041.1682.zip)

**Comment by KingAndJiang** [comment]
非常感谢

**Comment by hsk960219** [comment]
termsrv.dll 10.0.19041.1741   版本不支持SuperRDP

**Comment by anhkgg** [comment]
https://github.com/anhkgg/SuperRDP/releases/tag/v2.1.0.1
