### ISSUE TITLE
termsrv.dll 10.0.19041.1741

### ISSUE THREAD

**Issue by gelong** [anhkgg/SuperRDP#165]
[+] termsrv.dll 10.0.19041.1741
[-] Not support the version of termsrv, please [contact](url) author to update
[termsrv.zip](https://github.com/anhkgg/SuperRDP/files/9030051/termsrv.zip)

谢谢

**Comment by hsk960219** [comment]
同问 termsrv.dll 10.0.19041.1741

**Comment by anhkgg** [comment]
直接下载SuperRDP2，开启自动支持
