### ISSUE TITLE
termsrv.dll 10.0.19041.1682

### ISSUE THREAD

**Issue by chenzhonzhou** [anhkgg/SuperRDP#167]
[+] Select option 1, install...
[*] Installing...
[+] termsrv.dll 10.0.19041.1682
[-] Not support the version of termsrv, please contact author to update
[termsrv 10.0.19041.1682.zip](https://github.com/anhkgg/SuperRDP/files/9043697/termsrv.10.0.19041.1682.zip)

前几天启动不了，安装时提示termsrv.dll 10.0.19041.1682，以上是termsrv.dll 文件，使用的是V1 SuperRDP 有劳更新

**Comment by anhkgg** [comment]
直接下载最新的SuperRDP2吧，自动支持
