### ISSUE TITLE
Not supported - v10.0.19041.1741

### ISSUE THREAD

**Issue by ricardovalmada** [anhkgg/SuperRDP#168]
![2022-07-08 17_45_59-SuperRDP2 _ www hankeer org](https://user-images.githubusercontent.com/97296257/178067879-409f96f4-b32b-42a6-981e-4bb391e027a8.png)
[10.0.19041.1741.zip](https://github.com/anhkgg/SuperRDP/files/9074944/10.0.19041.1741.zip)

**Comment by anhkgg** [comment]
enable checkbox AutoSupport
