### ISSUE TITLE
系统版本号windows 10 10.0.19044.1826     termsrv 10.0.19041.1741 不支持安装

### ISSUE THREAD

**Issue by Oldpit** [anhkgg/SuperRDP#177]
系统版本号windows 10 10.0.19044.1826 
[10.0.19041.1741.zip](https://github.com/anhkgg/SuperRDP/files/9276126/10.0.19041.1741.zip)
我这个版本的不可以
![image](https://user-images.githubusercontent.com/12679808/183274151-1bcc9ef5-e98d-4a50-8e5e-24b0af38077f.png)

**Comment by anhkgg** [comment]
https://github.com/anhkgg/SuperRDP/releases/tag/v2.1.0.1
