### ISSUE TITLE
希望支持win7旗舰版

### ISSUE THREAD

**Issue by waynevan** [anhkgg/SuperRDP#18]
图片链接：
https://imgtu.com/i/WhfK9f

文字内容：
--------------------------------------------------------
---------SuperRDP for Windows 10 Home Version-----------
-------------Copyright (c) 2021 anhkgg.com--------------
-------------anhkgg | 公众号：汉客儿 -------------------
--------------------------------------------------------

--------------------------------------------------------

[+] SuperRDP initialize...

[*] SuperRDP already installed? 【No!】

[+] SuperRDP initialize success...

--------------------------------------------------------

Please select option:
    1: Install SuperRDP to Program Files folder (default)
    2: Uninstall SuperRDP
    3: Force restart Terminal Services

> 1
[+] Select option 1, install...
[*] Installing...
[+] termsrv.dll 6.1.7601.24402
[-] Not support the version of termsrv, please contact author to update.
请按任意键继续. . .

**Comment by anhkgg** [comment]
win7都停止服务了，不考虑支持。
另外原始版本应该支持win7
