### ISSUE TITLE
口令错误

### ISSUE THREAD

**Issue by febxby** [anhkgg/SuperRDP#194]
时区没错，先前还能用的
![c11bdc62dc3527fdc7e238f39dffe6a](https://user-images.githubusercontent.com/83848836/191167970-af03fbf7-8287-4002-949b-def8f3b4ae4f.jpg)

**Comment by febxby** [comment]
[termsrv.zip](https://github.com/anhkgg/SuperRDP/files/9604176/termsrv.zip)

**Comment by xiaojinyu-hhu** [comment]
我也是一样的问题，请问您是怎么解决的

**Comment by febxby** [comment]
> 我也是一样的问题，请问您是怎么解决的

自动好的
