### ISSUE TITLE
10.0.19044.2006 not support?

### ISSUE THREAD

**Issue by Deladrians** [anhkgg/SuperRDP#195]
i need help guys :1

![Captura de pantalla 2022-09-20 134722](https://user-images.githubusercontent.com/44852352/191250110-1c51b9db-ec7e-40bc-8112-6f7d16919b00.png)

[10.0.19041.1949.zip](https://github.com/anhkgg/SuperRDP/files/9607283/10.0.19041.1949.zip)

**Comment by Shbinging** [comment]
need support too

**Comment by anhkgg** [comment]
https://github.com/anhkgg/SuperRDP/releases/tag/v2.1.0.1
