### ISSUE TITLE
 termsrv.dll 10.0.19041.746 NOT SUPPORT

### ISSUE THREAD

**Issue by mdreamfly** [anhkgg/SuperRDP#2]
[+] Select option 1, install...
[*] Installing...
[+] termsrv.dll 10.0.19041.746
[-] Not support the version of termsrv, please contact author to update.

**Comment by anhkgg** [comment]
Get the new rdpwrap.ini in master.
https://github.com/anhkgg/SuperRDP/blob/main/bin/rdpwrap.ini

**Comment by mdreamfly** [comment]
my termsrv.dll version is 10.0.19041.746 , at the same time, I also got the latest ini, but I still got an error

thank you
