### ISSUE TITLE
10.0.22000.1098

### ISSUE THREAD

**Issue by yuanweize** [anhkgg/SuperRDP#202]
[superrdp.zip](https://github.com/anhkgg/SuperRDP/files/9793245/superrdp.zip)

**Comment by yuanweize** [comment]
> [superrdp.zip](https://github.com/anhkgg/SuperRDP/files/9793245/superrdp.zip)

By auto  analyze

**Comment by anhkgg** [comment]
https://github.com/anhkgg/SuperRDP/releases/tag/v2.1.0.1
