### ISSUE TITLE
VIRUS

### ISSUE THREAD

**Issue by sterno900** [anhkgg/SuperRDP#203]
Windows Defender detect a  virus
[https://i.ibb.co/MCDbjcw/virus.jpg](url)

**Comment by lahma0** [comment]
If you scan the file on VirusTotal, you will see that it is clearly labeled by the vast majority of virus scanners as "Not a Virus". Ex: 
`Not-a-virus:RemoteAdmin.Win64.RDPWrap.m`
This is simply indicating that the virus scanning software has recognized it as a tool that CAN be used for malicious purposes. There are a great many remote networking tools that are labeled as such. One such example off the top of my head would be netcat.
