### ISSUE TITLE
10.0.19041.2075版本

### ISSUE THREAD

**Issue by still-run-deep** [anhkgg/SuperRDP#215]
termsrv.dll 10.0.19041.2075 not supported
[termsrv.zip](https://github.com/anhkgg/SuperRDP/files/9989381/termsrv.zip)

**Comment by still-run-deep** [comment]
this ini works
[rdpwrap.zip](https://github.com/anhkgg/SuperRDP/files/9989917/rdpwrap.zip)

**Comment by Charlie-king** [comment]
thank you, It works

**Comment by anhkgg** [comment]
https://github.com/anhkgg/SuperRDP/releases/tag/v2.1.0.1
