### ISSUE TITLE
10.0.22621.819

### ISSUE THREAD

**Issue by TseawYangDzurn** [anhkgg/SuperRDP#217]
[termsrv.zip](https://github.com/anhkgg/SuperRDP/files/9998185/termsrv.zip)

**Comment by EasonTong** [comment]
我昨天晚上更新也是费了 2022年11月14日16:57:38

**Comment by imnbug** [comment]
球球快点更新吧！

**Comment by anhkgg** [comment]
我更新了ini，你们试一下，可不可以都给我同步一下消息，谢谢。

自动更新不能正常工作吗？

**Comment by TseawYangDzurn** [comment]
> 

系统：10.0.22621.819
termsrv：10.0.22621.608

抱歉之前写的不详细。现在将两个号码都附上。不过刚试过了，还是不行。

**Comment by anhkgg** [comment]
https://github.com/anhkgg/SuperRDP/releases/tag/v2.1.0.1
