### ISSUE TITLE
10.0.22000.1042

### ISSUE THREAD

**Issue by jeccyyeah** [anhkgg/SuperRDP#218]
win11,tks

[termsrv.zip](https://github.com/anhkgg/SuperRDP/files/10074525/termsrv.zip)

**Comment by loyejaotdiqr47123** [comment]
[10.0.22000.1042]
LocalOnlyPatch.x64=1
LocalOnlyOffset.x64=99651
LocalOnlyCode.x64=jmpshort
SingleUserPatch.x64=1
SingleUserOffset.x64=18F22
SingleUserCode.x64=Zero
DefPolicyPatch.x64=1
DefPolicyOffset.x64=1BD85
DefPolicyCode.x64=CDefPolicy_Query_eax_rcx
SLInitHook.x64=1
SLInitOffset.x64=277C0
SLInitFunc.x64=New_CSLQuery_Initialize

[10.0.22000.1042-SLInit]
bInitialized.x64      =120ECC
bServerSku.x64        =120ED0
lMaxUserSessions.x64  =120ED4
bAppServerAllowed.x64 =120EDC
bRemoteConnAllowed.x64=120EE4
bMultimonAllowed.x64  =120EE8
ulMaxDebugSessions.x64=120EF0
bFUSEnabled.x64       =120EF4

**Comment by anhkgg** [comment]
test AutoSupport：https://github.com/anhkgg/SuperRDP/releases/tag/v2.1.0.1
