### ISSUE TITLE
Please update for Windows 11 ( 10.0.22621.819) 

### ISSUE THREAD

**Issue by petercncn** [anhkgg/SuperRDP#219]
[Windows 11 ( 10.0.22621.819).zip](https://github.com/anhkgg/SuperRDP/files/10105327/Windows.11.10.0.22621.819.zip)

Please update for Windows 11 ( 10.0.22621.819)

**Comment by loyejaotdiqr47123** [comment]
[10.0.22621.608]
SingleUserPatch.x64=1
SingleUserOffset.x64=C283
SingleUserCode.x64=Zero
DefPolicyPatch.x64=1
DefPolicyOffset.x64=1C135
DefPolicyCode.x64=CDefPolicy_Query_eax_rcx
LocalOnlyPatch.x64=1
LocalOnlyOffset.x64=9B7E1
LocalOnlyCode.x64=jmpshort
SLInitHook.x64=1
SLInitOffset.x64=286D0
SLInitFunc.x64=New_CSLQuery_Initialize

[10.0.22621.608-SLInit]
bServerSku.x64=128F30
bRemoteConnAllowed.x64=128F44
bFUSEnabled.x64=128F54
bAppServerAllowed.x64=128F3C
bMultimonAllowed.x64=128F48
lMaxUserSessions.x64=128F34
ulMaxDebugSessions.x64=128F50
bInitialized.x64=128F2C

**Comment by anhkgg** [comment]
test AutoSupport：https://github.com/anhkgg/SuperRDP/releases/tag/v2.1.0.1
