### ISSUE TITLE
[版本 10.0.19044.2251]不兼容

### ISSUE THREAD

**Issue by bluetree2009** [anhkgg/SuperRDP#222]
无法运行 SuperRDp或者 superRDP2

请版本解决，谢谢

**Comment by bluetree2009** [comment]
[+] Select option 1, install...
[*] Installing...
[+] termsrv.dll 10.0.19041.2075
[-] Not support the version of termsrv, please contact author to update.

**Comment by anhkgg** [comment]
https://github.com/anhkgg/SuperRDP/releases/tag/v2.1.0.1
