### ISSUE TITLE
10.0.19041.2075

### ISSUE THREAD

**Issue by Matt-wzy** [anhkgg/SuperRDP#223]
[10.0.19041.2075.zip](https://github.com/anhkgg/SuperRDP/files/10171690/10.0.19041.2075.zip)

**Comment by loyejaotdiqr47123** [comment]
[10.0.19041.2075]
LocalOnlyPatch.x64=1
LocalOnlyOffset.x64=932F1
LocalOnlyCode.x64=jmpshort
SingleUserPatch.x64=1
SingleUserOffset.x64=11DE2
SingleUserCode.x64=Zero
DefPolicyPatch.x64=1
DefPolicyOffset.x64=1F2A5
DefPolicyCode.x64=CDefPolicy_Query_eax_rcx
SLInitHook.x64=1
SLInitOffset.x64=2877C
SLInitFunc.x64=New_CSLQuery_Initialize

[10.0.19041.2075-SLInit]
bInitialized.x64 =125084
bServerSku.x64 =125088
lMaxUserSessions.x64 =12508C
bAppServerAllowed.x64 =125094
bRemoteConnAllowed.x64=12509C
bMultimonAllowed.x64 =1250A0
ulMaxDebugSessions.x64=1250A4
bFUSEnabled.x64 =1250A8

**Comment by Matt-wzy** [comment]
> [10.0.19041.2075] LocalOnlyPatch.x64=1 LocalOnlyOffset.x64=932F1 LocalOnlyCode.x64=jmpshort SingleUserPatch.x64=1 SingleUserOffset.x64=11DE2 SingleUserCode.x64=Zero DefPolicyPatch.x64=1 DefPolicyOffset.x64=1F2A5 DefPolicyCode.x64=CDefPolicy_Query_eax_rcx SLInitHook.x64=1 SLInitOffset.x64=2877C SLInitFunc.x64=New_CSLQuery_Initialize
> 
> [10.0.19041.2075-SLInit] bInitialized.x64 =125084 bServerSku.x64 =125088 lMaxUserSessions.x64 =12508C bAppServerAllowed.x64 =125094 bRemoteConnAllowed.x64=12509C bMultimonAllowed.x64 =1250A0 ulMaxDebugSessions.x64=1250A4 bFUSEnabled.x64 =1250A8

Thanks a lot
