### ISSUE TITLE
superrdp2无法运行

### ISSUE THREAD

**Issue by standin000** [anhkgg/SuperRDP#224]
win10 19042.1766 home版本
superrdp2 点击运行没有任何显示
SuperRDP_v1.0.42  不支持 termsrv.dll  10.0.19041.1741

**Comment by loyejaotdiqr47123** [comment]
[RDPWrap-v1.7.5.zip](https://github.com/anhkgg/SuperRDP/files/10526702/RDPWrap-v1.7.5.zip)
请下载rdpwrap-v1.7.5，解压运行install.bat，安装成功后点击rdpconf.exe看看是否全绿即可

**Comment by standin000** [comment]
> [RDPWrap-v1.7.5.zip](https://github.com/anhkgg/SuperRDP/files/10526702/RDPWrap-v1.7.5.zip) 请下载rdpwrap-v1.7.5，解压运行install.bat，安装成功后点击rdpconf.exe看看是否全绿即可

不是运行后无法远程桌面，而是无法运行，所以rdpconf.exe不可能全绿的

**Comment by loyejaotdiqr47123** [comment]
那请问您的cpu框架是什么，rdpwrap是基于x64的

**Comment by standin000** [comment]
> 那请问您的cpu框架是什么，rdpwrap是基于x64的

是x64，但我的windows是home版本，这有关系吗？有办法让SuperRDP2.exe输出日志吗，我不知道它为啥不能启动

**Comment by loyejaotdiqr47123** [comment]
> win10 19042.1766 home版本 superrdp2 点击运行没有任何显示 SuperRDP_v1.0.42 不支持 termsrv.dll 10.0.19041.1741

您这是不支持这个版本，而我的rdpwrap-v1.7.5是支持的

**Comment by standin000** [comment]
> > win10 19042.1766 home版本 superrdp2 点击运行没有任何显示 SuperRDP_v1.0.42 不支持 termsrv.dll 10.0.19041.1741
> 
> 您这是不支持这个版本，而我的rdpwrap-v1.7.5是支持的

您是说superrdp2 不支持win10 x64 home版本吗？

**Comment by anhkgg** [comment]
https://github.com/anhkgg/SuperRDP/releases/tag/v2.1.0.1
