### ISSUE TITLE
10.0.22621.317

### ISSUE THREAD

**Issue by df2k** [anhkgg/SuperRDP#227]
windows11
termsrv.dll 10.0.22621.317

[termsrv.zip](https://github.com/anhkgg/SuperRDP/files/10342755/termsrv.zip)

[+] Select option 1, install...
[*] Installing...
[+] termsrv.dll 10.0.22621.317
[-] Not support the version of termsrv, please contact author to update.

**Comment by loyejaotdiqr47123** [comment]
[10.0.22621.317]
LocalOnlyPatch.x64=1
LocalOnlyOffset.x64=9B7E1
LocalOnlyCode.x64=jmpshort
SingleUserPatch.x64=1
SingleUserOffset.x64=186B2
SingleUserCode.x64=Zero
DefPolicyPatch.x64=1
DefPolicyOffset.x64=1C135
DefPolicyCode.x64=CDefPolicy_Query_eax_rcx
SLInitHook.x64=1
SLInitOffset.x64=286D0
SLInitFunc.x64=New_CSLQuery_Initialize

[10.0.22621.317-SLInit]
bInitialized.x64      =128F2C
bServerSku.x64        =128F30
lMaxUserSessions.x64  =128F34
bAppServerAllowed.x64 =128F3C
bRemoteConnAllowed.x64=128F44
bMultimonAllowed.x64  =128F48
ulMaxDebugSessions.x64=128F50
bFUSEnabled.x64       =128F54

**Comment by anhkgg** [comment]
使用自动分析：https://github.com/anhkgg/SuperRDP/releases/tag/v2.1.0.1
