### ISSUE TITLE
10.0.19041.1949

### ISSUE THREAD

**Issue by HeiZiSama** [anhkgg/SuperRDP#228]
[termsrv.zip](https://github.com/anhkgg/SuperRDP/files/10476119/termsrv.zip)

**Comment by loyejaotdiqr47123** [comment]
[10.0.19041.1949]
LocalOnlyPatch.x86=1
LocalOnlyOffset.x86=C2749
LocalOnlyCode.x86=jmpshort
SingleUserPatch.x86=1
SingleUserOffset.x86=3CAE7
SingleUserCode.x86=Zero
DefPolicyPatch.x86=1
DefPolicyOffset.x86=3E0B9
DefPolicyCode.x86=CDefPolicy_Query_eax_ecx
SLInitHook.x86=1
SLInitOffset.x86=6F388
SLInitFunc.x86=New_CSLQuery_Initialize
LocalOnlyPatch.x64=1
LocalOnlyOffset.x64=922A1
LocalOnlyCode.x64=jmpshort
SingleUserPatch.x64=1
SingleUserOffset.x64=11902
SingleUserCode.x64=Zero
DefPolicyPatch.x64=1
DefPolicyOffset.x64=1EDC5
DefPolicyCode.x64=CDefPolicy_Query_eax_rcx
SLInitHook.x64=1
SLInitOffset.x64=2665C
SLInitFunc.x64=New_CSLQuery_Initialize

[10.0.19041.1949-SLInit]
bInitialized.x86 =E398C
bServerSku.x86 =E3990
lMaxUserSessions.x86 =E3994
bAppServerAllowed.x86 =E399C
bRemoteConnAllowed.x86=E39A4
bMultimonAllowed.x86 =E39A8
ulMaxDebugSessions.x86=E39AC
bFUSEnabled.x86 =E39B0
bInitialized.x64 =124084
bServerSku.x64=124088
lMaxUserSessions.x64 =12408C
bAppServerAllowed.x64 =124094
bRemoteConnAllowed.x64=12409C
bMultimonAllowed.x64 =1240A0
ulMaxDebugSessions.x64=1240A4
bFUSEnabled.x64 =1240A8

**Comment by HeiZiSama** [comment]
> 



> [10.0.19041.1949] LocalOnlyPatch.x86=1 LocalOnlyOffset.x86=C2749 LocalOnlyCode.x86=jmpshort SingleUserPatch.x86=1 SingleUserOffset.x86=3CAE7 SingleUserCode.x86=Zero DefPolicyPatch.x86=1 DefPolicyOffset.x86=3E0B9 DefPolicyCode.x86=CDefPolicy_Query_eax_ecx SLInitHook.x86=1 SLInitOffset.x86=6F388 SLInitFunc.x86=New_CSLQuery_Initialize LocalOnlyPatch.x64=1 LocalOnlyOffset.x64=922A1 LocalOnlyCode.x64=jmpshort SingleUserPatch.x64=1 SingleUserOffset.x64=11902 SingleUserCode.x64=Zero DefPolicyPatch.x64=1 DefPolicyOffset.x64=1EDC5 DefPolicyCode.x64=CDefPolicy_Query_eax_rcx SLInitHook.x64=1 SLInitOffset.x64=2665C SLInitFunc.x64=New_CSLQuery_Initialize
> 
> [10.0.19041.1949-SLInit] bInitialized.x86 =E398C bServerSku.x86 =E3990 lMaxUserSessions.x86 =E3994 bAppServerAllowed.x86 =E399C bRemoteConnAllowed.x86=E39A4 bMultimonAllowed.x86 =E39A8 ulMaxDebugSessions.x86=E39AC bFUSEnabled.x86 =E39B0 bInitialized.x64 =124084 bServerSku.x64=124088 lMaxUserSessions.x64 =12408C bAppServerAllowed.x64 =124094 bRemoteConnAllowed.x64=12409C bMultimonAllowed.x64 =1240A0 ulMaxDebugSessions.x64=1240A4 bFUSEnabled.x64 =1240A8

有联系方式嘛。。因为似乎服务有点奇怪，不能正常运行

**Comment by loyejaotdiqr47123** [comment]
> 

那请加下QQ吧
130194352
