### ISSUE TITLE
Oneeva detected

### ISSUE THREAD

**Issue by mauro-miatello** [anhkgg/SuperRDP#23]
Microsoft antimalware detects onneva trojan in superrdp archive
![ksnip_20210831-092709](https://user-images.githubusercontent.com/11910225/131461795-20904632-889f-4a25-bac3-f1b20e80015f.png)

**Comment by susing** [comment]
看上去是加了广告, 兄弟能不能弄个收费版把广告模块卸了

**Comment by anhkgg** [comment]
开源的，看代码，哪里有广告
