### ISSUE TITLE
Windows 10

### ISSUE THREAD

**Issue by baolizhu** [anhkgg/SuperRDP#233]
10.0.22621.1105

**Comment by loyejaotdiqr47123** [comment]
请上传termsrv.dll
Please upload termsrv.dll

**Comment by loyejaotdiqr47123** [comment]
在系统版本10.0.22621.1105中找到的termsrv.dll版本为10.0.22621.1，以下是配置文件请将其添加至superrdp.ini
The version of termsrv.dll found in system version 10.0.22621.1105 is 10.0.22621.1, here is the configuration file please add it to superrdp.ini

**Comment by loyejaotdiqr47123** [comment]
[10.0.22621.1]
LocalOnlyPatch.x64=1
LocalOnlyOffset.x64=9B7E1
LocalOnlyCode.x64=jmpshort
SingleUserPatch.x64=1
SingleUserOffset.x64=186B2
SingleUserCode.x64=Zero
DefPolicyPatch.x64=1
DefPolicyOffset.x64=1C135
DefPolicyCode.x64=CDefPolicy_Query_eax_rcx
SLInitHook.x64=1
SLInitOffset.x64=286D0
SLInitFunc.x64=New_CSLQuery_Initialize

[10.0.22621.1-SLInit]
bInitialized.x64      =128F2C
bServerSku.x64        =128F30
lMaxUserSessions.x64  =128F34
bAppServerAllowed.x64 =128F3C
bRemoteConnAllowed.x64=128F44
bMultimonAllowed.x64  =128F48
ulMaxDebugSessions.x64=128F50
bFUSEnabled.x64       =128F54

**Comment by anhkgg** [comment]
使用自动分析：https://github.com/anhkgg/SuperRDP/releases/tag/v2.1.0.1

**Comment by loyejaotdiqr47123** [comment]
@anhkgg 我建议您还是更新superrdp2.ini的偏移值，因为部分用户反应自动更新不能用
