### ISSUE TITLE
初始化异常

### ISSUE THREAD

**Issue by dawnlau** [anhkgg/SuperRDP#236]
打开之后提示“初始化异常”，错误代码`c0000001`.

**Comment by dawnlau** [comment]
[termsrv.zip](https://github.com/anhkgg/SuperRDP/files/10820791/termsrv.zip)

**Comment by dawnlau** [comment]
![fail](https://user-images.githubusercontent.com/18576116/221095609-bee8f1ed-1e5a-4938-af73-9512598c835a.jpg)

**Comment by dawnlau** [comment]
win11 工作站版，21H2，22000.1641

**Comment by loyejaotdiqr47123** [comment]
请附上截图

**Comment by loyejaotdiqr47123** [comment]
我建议使用rdpwrap-v1.7.5，这个初始化异常可能是superrdp2本身的问题
[RDPWrap-v1.7.5.zip](https://github.com/anhkgg/SuperRDP/files/10830021/RDPWrap-v1.7.5.zip)
点击install.bat安装即可

**Comment by anhkgg** [comment]
写配置失败了，可能是其他安全软件组织了。

**Comment by dawnlau** [comment]
未安装其他安全软件，只有默认的Windows Defender
