### ISSUE TITLE
新版无法使用.

### ISSUE THREAD

**Issue by cweijan** [anhkgg/SuperRDP#238]
![image](https://user-images.githubusercontent.com/27798227/221743124-5e3cd7c1-31e2-430b-b99c-e6ad14bf8fba.png)

**Comment by Supremesir** [comment]
+1

**Comment by yf718** [comment]
+1

**Comment by fanchencloud** [comment]
+1

**Comment by anhkgg** [comment]
[commit](https://github.com/anhkgg/SuperRDP/commit/219041936b82f20b3df8a5b4c7984ed82ee64813)

**Comment by anhkgg** [comment]
https://github.com/anhkgg/SuperRDP/commit/4aa2bac678d76001b22d4e81f45445994060d90b
