### ISSUE TITLE
更新系统后无法远程。

### ISSUE THREAD

**Issue by michelleshao828** [anhkgg/SuperRDP#239]
[10.0.19041.2673.zip](https://github.com/anhkgg/SuperRDP/files/10985324/10.0.19041.2673.zip)

多谢！

**Comment by pengmaochang** [comment]
![image](https://user-images.githubusercontent.com/15193139/225909214-fc15c9f6-015d-4e3e-b3b9-a8165e55bec9.png)

**Comment by anhkgg** [comment]
https://github.com/anhkgg/SuperRDP/issues/239#issuecomment-1473784477
别乱说啊。我代码做了什么改造，我说readme清楚的了啊。另外SuperRDP2可是我原创了。

**Comment by anhkgg** [comment]
用superrpd2同步最新配置，还不能用吗？


[10.0.19041.2673]
LocalOnlyPatch.x64=1
LocalOnlyOffset.x64=932F1
LocalOnlyCode.x64=jmpshort
SingleUserPatch.x64=1
SingleUserOffset.x64=11DE2
SingleUserCode.x64=Zero
DefPolicyPatch.x64=1
DefPolicyOffset.x64=1F2A5
DefPolicyCode.x64=CDefPolicy_Query_eax_rcx
SLInitHook.x64=1
SLInitOffset.x64=2877C
SLInitFunc.x64=New_CSLQuery_Initialize

[10.0.19041.2673-SLInit]
bInitialized.x64 =125084
bServerSku.x64 =125088
lMaxUserSessions.x64 =12508C
bAppServerAllowed.x64 =125094
bRemoteConnAllowed.x64=12509C
bMultimonAllowed.x64 =1250A0
ulMaxDebugSessions.x64=1250A4
bFUSEnabled.x64 =1250A8

**Comment by fzu021800901** [comment]
> > [10.0.19041.2673.zip](https://github.com/anhkgg/SuperRDP/files/10985324/10.0.19041.2673.zip)
> > 多谢！
> 
> @michelleshao828 兄弟，汉克这个东西是直接用的别人的源码来生成一个自动检查器。原项目在这：https://github.com/stascorp/rdpwrap/releases 下载最新版本的zip，然后解压后，打开其中的RDPConf.exe。勾上Enabel Remote Desktop即可

请问是怎么配置的，需要替换哪个文件
![image](https://user-images.githubusercontent.com/55173459/226082407-78eca0b0-4031-4b00-822a-eca0110eacaf.png)
