### ISSUE TITLE
termsrv version problem

### ISSUE THREAD

**Issue by taylorshineboy** [anhkgg/SuperRDP#27]
[+] Select option 1, install...
[*] Installing...
[+] termsrv.dll 10.0.17763.1697
[-] Not support the version of termsrv, please contact author to update.

but the setting shows that i am using 17763.1817

**Comment by anhkgg** [comment]
upload the file: c:\windows\system32\termsrv.dll

**Comment by taylorshineboy** [comment]
> upload the file: c:\windows\system32\termsrv.dll

我把termsrv.dll文件放在了system32目录下了，现在只能用一个账户登录，用另外的账户登陆时必须下线另一个账户，但是我已经允许多用户登陆了
![image](https://user-images.githubusercontent.com/43833906/133748771-e6a062ae-b5a7-4b97-83ee-afd4cd0b3de4.png)

**Comment by taylorshineboy** [comment]
[termsrv.zip](https://github.com/anhkgg/SuperRDP/files/7545988/termsrv.zip)
这是termsrv.dll文件，拜托支持一下
