### ISSUE TITLE
希望兼容 10.0.20348.143版本

### ISSUE THREAD

**Issue by 2213500360** [anhkgg/SuperRDP#28]
![2}O4PCKX@_@(YN$6GF0M}1](https://user-images.githubusercontent.com/67719519/134323689-97ac77a8-b091-418c-a3a7-1d896ef7a19e.png)

**Comment by anhkgg** [comment]
把C:\windows\system32\termsrv.dll上传上来给我

**Comment by anhkgg** [comment]
like this : #30
