### ISSUE TITLE
更新至10.0.26052.1100后，自动分析没有反应

### ISSUE THREAD

**Issue by SmilingEnchanter** [anhkgg/SuperRDP#281]
![image](https://github.com/anhkgg/SuperRDP/assets/117137250/f3ea7fc7-3afd-4b90-b95d-c7a96f9f5b4d)
更新前可正常使用，更新后勾选自动分析后再点击安装，仍提示“不支持，同步最新配置或者开启自动分析”，没有进行自动分析

**Comment by SmilingEnchanter** [comment]
[termsrv.zip](https://github.com/anhkgg/SuperRDP/files/14260446/termsrv.zip)

**Comment by loyejaotdiqr47123** [comment]
#282 你可以看下这个issues

**Comment by SmilingEnchanter** [comment]
> #282 你可以看下这个issues

解决了，感谢
所以是以后都用不了自动分析了吗qwq

**Comment by loyejaotdiqr47123** [comment]
> > #282 你可以看下这个issues
> 
> 解决了，感谢 所以是以后都用不了自动分析了吗qwq
貌似作者的网站被dns污染了，会自动跳转到非法网站
