### ISSUE TITLE
19042.782 安装失败

### ISSUE THREAD

**Issue by PercyDan54** [anhkgg/SuperRDP#3]
```[+] Select option 1, install...
[*] Installing...
[+] termsrv.dll 10.0.19041.782

[-] Not support the version of termsrv, please contact author to update.
```

![image](https://user-images.githubusercontent.com/50285552/106294319-fc6d5f80-6289-11eb-81e6-5ddd22026316.png)

**Comment by anhkgg** [comment]
我还没这个版本，你可以把这个版本的termsrv.dll发给我，网盘

**Comment by PercyDan54** [comment]
> 我还没这个版本，你可以把这个版本的termsrv.dll发给我，网盘

https://wwa.lanzous.com/iWwIDl5nmri

**Comment by anhkgg** [comment]
[](https://github.com/anhkgg/SuperRDP/releases/tag/v1.0.2)

**Comment by anhkgg** [comment]
https://github.com/anhkgg/SuperRDP/releases/tag/v1.0.2
