### ISSUE TITLE
没有termsrv服务，用rdp wrap跑了也不行

### ISSUE THREAD

**Issue by jingxdy** [anhkgg/SuperRDP#314]
[termsrv.dll.zip](https://github.com/user-attachments/files/15910624/termsrv.dll.zip)
![image](https://github.com/anhkgg/SuperRDP/assets/93567493/5e865053-6c33-4605-93fd-664a2ac646bf)

**Comment by loyejaotdiqr47123** [comment]
[TermService.zip](https://github.com/user-attachments/files/15911910/TermService.zip)
覆盖一下注册表看下

**Comment by jingxdy** [comment]
覆盖注册表，问题解决了，但是3389端口还是no，系统版本是10.0.22631.3737，termsrv是10.0.22621.3672

**Comment by jingxdy** [comment]
[termsrv.zip](https://github.com/user-attachments/files/15924360/termsrv.zip)

**Comment by jingxdy** [comment]
抱歉，我重启，问题就好了
