### ISSUE TITLE
是什么原因这么多报红？让人惊疑不定

### ISSUE THREAD

**Issue by InvLabTech** [anhkgg/SuperRDP#318]
如图
![image](https://github.com/user-attachments/assets/f5bde983-e442-4fff-a939-d66ee63562c0)

**Comment by InvLabTech** [comment]
我刚刚去官网发了评论询问，重进看不到我的评论。这什么鬼

**Comment by anhkgg** [comment]
看到报的字样了吗，vmprotect，这种基本都是加壳误报
