### ISSUE TITLE
22494.1000不支持，希望添加

### ISSUE THREAD

**Issue by OrangeCh** [anhkgg/SuperRDP#37]

**Comment by OrangeCh** [comment]
![image](https://user-images.githubusercontent.com/9038816/140639178-77867f48-a591-4802-be6b-d6db9a5acfa7.png)

**Comment by anhkgg** [comment]
c:\windows\system32\termsrv.dll传上来

**Comment by OrangeCh** [comment]
[termsrv.zip](https://github.com/anhkgg/SuperRDP/files/7492372/termsrv.zip)
Thanks
