### ISSUE TITLE
19043.1348 这个版本支持下嘛，谢谢

### ISSUE THREAD

**Issue by kbrownehs18** [anhkgg/SuperRDP#40]
万分感谢，今天莫名其妙升级了下就用不起了。

**Comment by anhkgg** [comment]
上传c:\windows\system32\termsrv.dll

**Comment by kbrownehs18** [comment]
[termsrv.zip](https://github.com/anhkgg/SuperRDP/files/7516737/termsrv.zip)

**Comment by wendaoshenyang** [comment]
是19042.1348吧

**Comment by kbrownehs18** [comment]
![image](https://user-images.githubusercontent.com/41469997/141224400-f3dbd3fd-3631-4aac-bcd5-5aeed8100c5f.png)

**Comment by wendaoshenyang** [comment]
行吧，那确实是不一样，我也是晚上更新后就不支持了
![image](https://user-images.githubusercontent.com/19400927/141225522-9eede725-e452-4fdf-9461-d0f9671c5ccf.png)
