### ISSUE TITLE
19042.1348 这个版本请求支持，多谢大神

### ISSUE THREAD

**Issue by wendaoshenyang** [anhkgg/SuperRDP#41]
[termsrv.zip](https://github.com/anhkgg/SuperRDP/files/7517012/termsrv.zip)

**Comment by anhkgg** [comment]
[https://github.com/anhkgg/SuperRDP/commit/90dc95c83283098ee2ab2499c14409472f89ee38](https://github.com/anhkgg/SuperRDP/commit/90dc95c83283098ee2ab2499c14409472f89ee38)
