### ISSUE TITLE
19042.789 please!

### ISSUE THREAD

**Issue by Chaser-wind** [anhkgg/SuperRDP#5]
19042.789 please!

**Comment by anhkgg** [comment]
Please upload the file termsrv.dll

**Comment by Chaser-wind** [comment]
[termsrv.zip](https://github.com/anhkgg/SuperRDP/files/5943701/termsrv.zip)
This is termsrv.dll from C:/Windows/System32. Thanks!

**Comment by anhkgg** [comment]
https://github.com/anhkgg/SuperRDP/releases/tag/v1.0.3
