### ISSUE TITLE
16 bit application?

### ISSUE THREAD

**Issue by MrM40** [anhkgg/SuperRDP#51]
What am I missing?

When I run `SuperRDP.exe update` i get this error:

![16bit](https://user-images.githubusercontent.com/16258063/143019015-d212c21d-c501-418b-af7a-04a049c5015e.jpg)

**Comment by MrM40** [comment]
Ahh....I ran the compiled version in  the bin folder which seem to very old.
Perhaps it should be updated or removed ;-)

**Comment by anhkgg** [comment]
https://github.com/anhkgg/SuperRDP/releases/download/v1.0.22/SuperRDP_v1.0.22.zip
