### ISSUE TITLE
感谢作者 请添加对10.0.19041.1387的支持

### ISSUE THREAD

**Issue by PeisongZou** [anhkgg/SuperRDP#53]
感谢作者开发这么好的软件！实在是太有用了！我一定会进行捐赠！
另外，今天发现我的termsrv又更新了，版本10.0.19041.1387不支持，作者方便更新一下吗？
[termsrv.zip](https://github.com/anhkgg/SuperRDP/files/7606279/termsrv.zip)
？

**Comment by ner00** [comment]
Does not work.
TermService fails to start with this patch.
