### ISSUE TITLE
12月7日的更新导致此软件失效，版本为10.0.17763.1369，dll文件在附件的压缩包中

### ISSUE THREAD

**Issue by SunnyHong36** [anhkgg/SuperRDP#57]
昨日的系统更新导致此软件，包括原版RdpWrap失效了，这是最新的DLL，谢谢！
[termsrv.zip](https://github.com/anhkgg/SuperRDP/files/7674927/termsrv.zip)

**Comment by fa1247** [comment]
在Rdpwrap的的issue中找到了对应的ini，实测可用。
https://github.com/stascorp/rdpwrap/issues/1617
