### ISSUE TITLE
SuperRDP can't support my version, This is my c:\windows\system32\termsrv.dll ,think you .

### ISSUE THREAD

**Issue by leiyuleiyu** [anhkgg/SuperRDP#58]
SuperRDP can't support my version, This is my c:\windows\system32\termsrv.dll ,think you .
Windows 10 home 家庭中文版
20H2
19042.134
[termsrv.zip](https://github.com/anhkgg/SuperRDP/files/7700220/termsrv.zip)
termsrv版本号:10.0.19041.1348

**Comment by anhkgg** [comment]
https://github.com/anhkgg/SuperRDP/releases/tag/v1.0.20
