### ISSUE TITLE
系统19042.804安装失败

### ISSUE THREAD

**Issue by ssdlh1999** [anhkgg/SuperRDP#6]
Windows系统版本是19042.804，rdpwrap.ini里面有10.0.19041.789，但是安装的时候会报错，不支持该版本
termsrv.dll 10.0.19041.789
Not support the version of termsrv, please connect the author to update

**Comment by anhkgg** [comment]
你下载新的了吗？

**Comment by ssdlh1999** [comment]
是的。打开ini确实是有10.0.19041.789，但是安装总是提示不支持该版本

**Comment by ssdlh1999** [comment]
是的。打开ini看，确实是有10.0.19041.789，但是安装总是提示不支持该版本



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Anhkgg"<notifications@github.com&gt;; 
发送时间: 2021年3月5日(星期五) 上午9:55
收件人: "anhkgg/SuperRDP"<SuperRDP@noreply.github.com&gt;; 
抄送: "蓝蓝的蓝"<747948852@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [anhkgg/SuperRDP] 系统19042.804安装失败 (#6)





 
你下载新的了吗？

**Comment by Demprace** [comment]
遇到了同一个问题，之前版本装上的，系统更新不能用之后搞错给卸载了，下了新版来安装就出现了这个问题。

**Comment by anhkgg** [comment]
问题已经修复
