### ISSUE TITLE
新配的电脑现在安装了win11,SuperRDP是否能支持win11了？谢谢。

### ISSUE THREAD

**Issue by yiyi99** [anhkgg/SuperRDP#63]
SuperRDP是否能支持win11了？谢谢。

**Comment by anhkgg** [comment]
支持，如果版本没有，可以上传c:\windows\system32\termsrv.dll，我加上

**Comment by reboot1921** [comment]
@yiyi99 您好，您fork了我这边的一个项目，比较紧急，看到请联系我下哈 1511749834@qq.com
