### ISSUE TITLE
Not support the version of termsrv, please contact author to update.

### ISSUE THREAD

**Issue by nash-R** [anhkgg/SuperRDP#64]
[*] Installing...
[+] termsrv.dll 6.1.7601.24402
[-] Not support the version of termsrv, please contact author to update.

我的win7不支持。。。
[termsrv.zip](https://github.com/anhkgg/SuperRDP/files/7791692/termsrv.zip)

**Comment by lyrasean** [comment]
Win7就挺难了，我看了作者目前发布的25版，最低要求是Win10 V1809/RS5 10.0.17763。
而且我发现系统版本和termsrv.dll版本之间存在兼容性问题，这也是为什么系统版本更新了，termsrv.dll也要更新。
系统版本10.0.17763.107安装termsrv.dll 10.0.17763.1就会出现APPCRASH的问题，Remote Desktop Services会自动关闭。
而系统版本10.0.17763.2366安装termsrv.dll 10.0.17763.2300就能正常工作。

**Comment by lyrasean** [comment]
额，忘了Win7可以用原来的[rdpwrap](https://github.com/stascorp/rdpwrap)啊

**Comment by anhkgg** [comment]
是的，用老的
