### ISSUE TITLE
win10 19044.1415暂无支持

### ISSUE THREAD

**Issue by Qeynos** [anhkgg/SuperRDP#68]
[termsrv.zip](https://github.com/anhkgg/SuperRDP/files/7832971/termsrv.zip)
版本为10.0.19041.1387

**Comment by Qeynos** [comment]
好像之前有添加，又删掉了，不知为何

**Comment by anhkgg** [comment]
https://github.com/anhkgg/SuperRDP/commit/0bb364be0add26b0634a53c69d9205ef228a6eee

**Comment by Qeynos** [comment]
> [0bb364b](https://github.com/anhkgg/SuperRDP/commit/0bb364be0add26b0634a53c69d9205ef228a6eee)

第二次更新又取消了支持，这是为什么呢

**Comment by Qeynos** [comment]
> [0bb364b](https://github.com/anhkgg/SuperRDP/commit/0bb364be0add26b0634a53c69d9205ef228a6eee)

是我没看明白，我去试一下先
