### ISSUE TITLE
Not support the version of termsrv, please contact author to update.

### ISSUE THREAD

**Issue by weapons1990** [anhkgg/SuperRDP#73]
Can't install; my computer is win10

error is below

[+] termsrv.dll 10.0.17763.771
[-] Not support the version of termsrv, please contact author to update.

**Comment by anhkgg** [comment]
please upload c:\windows\system32\termsrv.dll

**Comment by anhkgg** [comment]
you can try : https://raw.githubusercontent.com/anhkgg/SuperRDP/main/bin/SuperRDP2.zip
