### ISSUE TITLE
Not support the version of termsrv, please contact author to update.

### ISSUE THREAD

**Issue by 1874tian** [anhkgg/SuperRDP#75]
termsrv.dll 10.0.19041.1387
Not support the version of termsrv, please contact author to update.
[termsrv.zip](https://github.com/anhkgg/SuperRDP/files/7931303/termsrv.zip)

**Comment by anhkgg** [comment]
try https://raw.githubusercontent.com/anhkgg/SuperRDP/main/bin/SuperRDP2.zip
