### ISSUE TITLE
Server 2022 - termsrv.dll 10.0.20348.143

### ISSUE THREAD

**Issue by hydro2k** [anhkgg/SuperRDP#77]
[+] termsrv.dll 10.0.20348.143
[-] Not support the version of termsrv, please contact author to update

attached in the .dll in question
[termsrv.zip](https://github.com/anhkgg/SuperRDP/files/7972067/termsrv.zip)
.

**Comment by WARLo0RD** [comment]
Patched termsrv.dll https://filespace.com/dva2zxcnwgp7 for the version Windows Server 2022
