### ISSUE TITLE
10.0.19041.1503  Not support the version of termsrv, please contact author to update.

### ISSUE THREAD

**Issue by Gavinin** [anhkgg/SuperRDP#79]

**Comment by anhkgg** [comment]
upload c:\windows\system32\termsrv.dll

**Comment by brumegoo** [comment]
[termsrv.zip](https://github.com/anhkgg/SuperRDP/files/8014921/termsrv.zip)
version 10.0.19041.1503
I find the termsrv.dll in this folder “C:\Windows\WinSxS\amd64_microsoft-windows-t..teconnectionmanager_31bf3856ad364e35_10.0.19041.1503_none_033ee8260992dc71”

**Comment by anhkgg** [comment]
Is there no termsrv.dll in c:\windows\system32?

**Comment by anhkgg** [comment]
Is there no termsrv.dll in c:\windows\system32 ?

**Comment by brumegoo** [comment]
> Is there no termsrv.dll in c:\windows\system32 ?

no, I find termsrv.dll in c:\windows\system32, too.
I search the termsrv.dll in [eveything](https://www.voidtools.com/), not find the termsrv.dll in system32 folder.

**Comment by liuli7700** [comment]
[termsrv_10.0.19041.1503.zip](https://github.com/anhkgg/SuperRDP/files/8022789/termsrv_10.0.19041.1503.zip)
my version is also 10.0.19041.1503, I found it in c:\windows\system32 @anhkgg

**Comment by anhkgg** [comment]
3q, The tow files are the same.
