### ISSUE TITLE
安装SuperRDP后tailscale服务无法打开了

### ISSUE THREAD

**Issue by byangmath** [anhkgg/SuperRDP#88]
安装SuperRDP后tailscale服务无法打开了。tailscale是我内网穿透用的。卸载SuperRDP后，tailscale服务依旧打不开，重启也没用

**Comment by anhkgg** [comment]
tailscale重装一下，是端口冲突了吗

**Comment by byangmath** [comment]
> tailscale重装一下，是端口冲突了吗

我该怎么查看是否端口冲突了呢？我重装了tailscale也没用。去tailscale官方解答那里删除了配置文件重新安装后终于出现log in按钮，但是点了没反应。实在没办法解决了，估计得重置系统了。我用谷歌搜索发现有些人升级了系统后也出现了我这样的问题，但我没有找到适合我的解决方法。
